# Service name
service: slackmonitor

# AWS details
provider:
  name: aws
  runtime: nodejs4.3
  region: eu-west-1
  deploymentBucket: nuk-tnl-editorial-prod-serverless-deployments

# Lambda functions
functions:
  slackmonitor:
    # Entry point
    handler: src/handler.handler
    # Function triggers
    events:
      - http:
          method: get
          path: /
      - http:
          method: post
          path: /
    # Env vars (from a separate env file)
    environment:
      CLIENT_ID: ${file(env.yml):CLIENT_ID}
      CLIENT_SECRET: ${file(env.yml):CLIENT_SECRET}
      REDIRECT_URI: ${file(env.yml):REDIRECT_URI}
